GET http://localhost:8000/api/v1/stores HTTP/1.1

###

POST http://localhost:8000/api/v1/stores HTTP/1.1
content-type: application/json

{
	"email": "test@test.com",
	"password": "password123"
}


###
